// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:TA_project/test.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter/material.dart';

// / Default [FirebaseConfig] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_Config.dart';
// / // ...
// / await Firebase.initializeApp(
// /   Config: DefaultFirebaseConfig.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCg56v-MNgGXQlszR81ySz33pTDgxH703M",
    authDomain: "taprojecttest-e3220.firebaseapp.com",
    projectId: "taprojecttest-e3220",
    storageBucket: "taprojecttest-e3220.firebasestorage.app",
    messagingSenderId: "97433726790",
    appId: "1:97433726790:web:ea0b661855a45acf347f47",
  );
}
